modLoader="javafml"

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="Fkn" #mandatory

version="1.15.2-1.0.0" #mandatory
displayName="Fast Knifes" #mandatory
credits="Thanks to TechnoVision for helping me with this mod." #optional
authors="Erik aka The_Shadow_LP4_ aka ShadowInTheSky" #optional
description='''
A mod that does some things and implements super fast Knifes
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
